name: Deploy Angular App to Amazon Linux EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t angular-app .

      - name: Save Docker image
        run: docker save angular-app | gzip > angular-app.tar.gz

      - name: Copy image to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "angular-app.tar.gz"
          target: "/home/ec2-user"

      - name: Deploy on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker load < angular-app.tar.gz
            docker stop angular-app || true
            docker rm angular-app || true
            docker run -d \
              --name angular-app \
              -p 80:80 \
              angular-app
